"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum

class ChannelType(str, Enum):
    SYSTEM = ...
    GLOBALS = ...
    PUBLIC = ...
    UNKNOWN = ...


@dataclass(frozen=True, slots=True)
class ChatLine:
    event_dt: datetime
    channel_type: ChannelType
    channel_token: str
    speaker: str
    message: str
    raw: str
    ...


