"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

@dataclass(frozen=True, slots=True)
class GenConfig:
	total_lines: int = ...
	p_system_mining: float = ...
	p_public: float = ...
	p_globals: float = ...
	p_tower_multiline: float = ...
	sleep_ms_min: int = ...
	sleep_ms_max: int = ...
	seed: int = ...


class ChatLogGenerator:
	"""
	Generates Entropia-like chat.log lines with realistic mining-related System messages,
	mixed with public channels and globals. Can optionally emit a rare multiline tower message.
	"""
	def __init__(self, cfg: GenConfig) -> None:
		...
	
	def iter_lines(self, start_dt: datetime | None = ...) -> Iterable[str]:
		"""
		Yield formatted chat.log lines.
		Timestamps are EU time (naive).
		"""
		...
	
	def write_file(self, path: Path, start_dt: datetime | None = ..., mode: str = ...) -> None:
		"""
		Write generated lines to a file.
		mode="a" for append (tail-friendly), mode="w" to overwrite.
		"""
		...
	


def generate_chat_log(path: str, cfg: GenConfig | None = ...) -> None:
	...

if __name__ == "__main__":
	...
